# Generated by Django 2.2.12 on 2022-10-09 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepId', models.IntegerField(verbose_name='Department ID')),
                ('DepName', models.CharField(max_length=120, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.IntegerField(max_length=10, verbose_name='Employee ID')),
                ('EmpName', models.CharField(max_length=120, verbose_name='Employee Name')),
                ('Salary', models.IntegerField(max_length=4, verbose_name='Salary')),
                ('Manager', models.CharField(max_length=300, verbose_name='Manager')),
                ('Location', models.CharField(max_length=15, verbose_name='Location')),
                ('DepartmentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
            ],
        ),
    ]
